stages:
  - deploy

deploy_staging:
  image: alpine:latest
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$REMOTERETRO_STG_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - ssh-keyscan -p 2244 $REMOTERETRO_STG >> ~/.ssh/known_hosts
  script:
    - ssh -p 2244 gitlab@$REMOTERETRO_STG "cd /docker/remoteretro-cnt && git pull origin development"
    - ssh -p 2244 gitlab@$REMOTERETRO_STG "cd /docker/remoteretro-cnt && docker compose up -d --force-recreate"
  only:
    - development

deploy_production:
  image: alpine:latest
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$REMOTERETRO_PROD_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - ssh-keyscan -p 20000 $REMOTERETRO_PROD >> ~/.ssh/known_hosts
  script:
    - ssh -p 20000 gitlab@$REMOTERETRO_PROD "cd /docker/remoteretro-cnt && git fetch --tags"
    - ssh -p 20000 gitlab@$REMOTERETRO_PROD "cd /docker/remoteretro-cnt && git checkout $CI_COMMIT_TAG"
    - ssh -p 20000 gitlab@$REMOTERETRO_PROD "cd /docker/remoteretro-cnt && docker compose up -d --build --force-recreate"
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
